export const UserActionTypes={
    USER_SAVE_POLL:'USER_SAVE_POLL',
    USER_SHOW_POLL_FORM:'USER_SHOW_POLL_FORM',
    USER_HIDE_POLL_FORM:'USER_HIDE_POLL_FORM',
    USER_OPTION_SELECT:'USER_OPTION_SELECT'


}
export const AdminActionTypes={
    ADD_POLL:'ADD_POLL',
    CLOSE_POLL:'CLOSE_POLL',
    SHOW_HIDE_POLL_FORM:'SHOW_HIDE_POLL_FORM',
    POLL_LABEL_CHANGE:'POLL_LABEL_CHANGE',
    QUESTION_LABEL_CHANGE:'QUESTION_LABEL_CHANGE',
    OPTION_VALUE_CHANGE:'OPTION_VALUE_CHANGE',
    ADD_OPTION:'ADD_OPTION',
    ADD_QUESTION:'ADD_QUESTION',
    SHOW_CHART:'SHOW_CHART',
    UPDATE_POLL:'UPDATE_POLL'

}
export const LoginActionTypes= {
    USER_SIGNUP:'USER_SIGNUP',
    USER_LOGIN:'USER_LOGIN',
    USER_LOGOUT:'USER_LOGOUT',
    USERNAME_CHANGE:'USERNAME_CHANGE',
    PASSWORD_CHANGE:'PASSWORD_CHANGE',
    TYPE_CHANGE:'TYPE_CHANGE',
    UPDATE_USER:'UPDATE_USER'
}